### PR TITLE
Add development notes.

### PR DESCRIPTION
**Pull request by matro**
For #22.

### CODE REVIEW

**Comment by X1011** [comment]
cool. i've made some changes in my own [dev-docs banch](https://github.com/X1011/git-directory-deploy/commits/dev-docs). I've moved the info to a separate file, because it's kind of a lot of text that not everyone needs to see, and GitHub has a nice [feature to point would-be contributors to it](https://help.github.com/articles/setting-guidelines-for-repository-contributors). (I'm hoping the filename doesn't actually need to be all caps, as was the case with the readme.)

i still want to work on the testing section some more, but let me know what you think.

**Comment by matro** [comment]
I did a quick test, and lower-case `contributors.md` triggers that fancy banner.

screeny1
screeny2

**Comment by matro** [comment]
Everything looks great to me, and :+1: to the changes on your branch off this too.

**Comment by matro** [comment]
Something I'm not sure about, with the RSpec/Mocha-style format for test names... should the indented tests be indented some set amount (I went with 8 spaces, I think), or should they be aligned with the non-indented one?

In other words, this...

```
deploy creates a branch
       commits to the right branch

args-parsing goes in the right order
             can handle spaces
```

...or this:

```
deploy creates a branch
	commits to the right branch

args-parsing goes in the right order
	can handle spaces
```

Just realized that I might've made a wrong assumption when writing my tests, and I don't know what RSpec or Mocha styles do.

**Comment by X1011** [comment]
yea, i noticed the discrepancy, but i didn't know which way i wanted to go, either. [Mocha](http://mochajs.org/#spec) and [RSpec](http://rspec.info/#asciicast-iframe-14103) use a fixed indentation size, but they also print the subject of a group or subgroup on its own line.

i was aligning with the pseudo-group subject for the tests i wrote, but that becomes less tenable as longer names are used.

i think i'm just going to go with whatever looks best on a case-by-case basis. We could probably pipe the output to a sed or awk command that would split the 1st line of each group so it looks like Mocha, but i'm not going to mess with that right now.

**Pull request merged**
