### PR TITLE
Add '-h', '--help' message.

### PR DESCRIPTION
**Pull request by matro**
Accounts for the last part of part of X1011/git-directory-deploy#14.

### CODE REVIEW

**Comment by matro** [comment]
I tried to keep it this pretty short and tight, with things in the same order as the args-parser rather than the readme file. If you want, I can try to move some content from the readme into the script as well, to de-dupe things a bit.

**Comment by matro** [comment]
If it turns out that 676d33f on #19 works out, I'll gladly revert 338c529 here and add that and do whatever else is needed to bring `--help` up to date with what's on master too.

**Comment by matro** [comment]
Same thing with #20 as well.

**Comment by X1011** [comment]
merged with some tweaks.

**Pull request merged**
